jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: ./paket.sh restore
    displayName: Restore packages
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
  - script: dotnet build src/BlackFox.Stidgen.Build/BlackFox.Stidgen.Build.fsproj
    displayName: Compile build script
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
  - script: ./build.sh CI
    displayName: Build
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: paket.exe restore
    displayName: Restore packages
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
  - script: dotnet build src/BlackFox.Stidgen.Build/BlackFox.Stidgen.Build.fsproj
    displayName: Compile build script
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
  - script: build.cmd CI
    displayName: Build
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
